### ISSUE TITLE
Material images

### ISSUE THREAD

**Issue by feralheart** [AustinTSchaffer/animal-crossing-crafting-recipe-database#2]
Can you add the material images to the JSON?

**Comment by AustinTSchaffer** [comment]
Good morning,

The top-level "raw_materials" object within the json document does contain some of the raw material images, but the wiki at the time did not have images for all raw materials, so most don't have an image url.

```python
import json
with open('./diy_recipes.json') as _json:
    data = json.load(_json)

raw = data['raw_materials']
len(raw)
### 121
raw_w_images = {k:v for k,v in raw.items() if v['image_url']}
len(raw_w_images)
### 54
```

I tried running a re-export but it looks like [the raw materials wiki page](https://animalcrossing.fandom.com/wiki/Crafting_materials_(New_Horizons)) has changed structurally since I wrote the script. I can work on getting the script working with the new page format.

Just out of curiosity, how do you intend to use the data?

**Comment by feralheart** [comment]
I would like to make an ACNH Telegram Bot

**Comment by AustinTSchaffer** [comment]
@feralheart I have updated the script and the data it exports.
