### ISSUE TITLE
ERR 503 when downloading the image

### ISSUE THREAD

**Issue by feralheart** [AustinTSchaffer/animal-crossing-crafting-recipe-database#3]
I tried to get the images from the JSON, but I got Error 503 when I wanted to reach the url in `imageurl` 
[Test URL](https://vignette.wikia.nocookie.net/animalcrossing/images/1/13/NH-Flimsy_axe.png/revision/latest?cb=20200325181711)

**Comment by AustinTSchaffer** [comment]
That url works for me

**Comment by AustinTSchaffer** [comment]
Couple of thoughts here.

Maybe your IP and user agent were flagged and blocked by https://vignette.wikia.nocookie.net/ or the content is blocked in your region.

Maybe some of the images that you're looking at in the data are out of date, indicating that someone needs to run a new data download job and make a pull request that includes the updated data. That will unfortunately break the raw_materials table as outlined in Issue #2. If this is the case, please refer to that issue thread.

If you're trying to include those images on your app using the URLs in the data, you're likely running into a CORS issue. Please don't rely on someone else's domain for hosting images that you intend to use for your own purposes. You should instead attempt to download all images to a assets folder or whatever format suits your needs and pull the resources from there. I only included those URLs for reference.

@feralheart, for any future issues, please provide more information in your issue and don't automatically assume that I'm going to solve all of your problems for you, technical or otherwise. Looking at other issues that you've posted around GitHub, you seem to have a habit of doing this. I appreciate that you're looking to use work and resources that I have provided to the world for free, but that's no excuse for rudeness.
